// 아직 인라인 스타일을 쓰는 매장 정보 편집 화면의 공통 컨트롤입니다.
// 대시보드의 레이아웃과 상태 컴포넌트는 styles/global.css에서 관리합니다.
export const dashboardStyles = {
  nameEdit: {
    display: 'flex',
    flexDirection: 'column',
    gap: 8,
    margin: '12px 0',
  },
  nameInput: {
    width: '100%',
    minWidth: 0,
    minHeight: 40,
    padding: '8px 11px',
    border: '1px solid var(--owner-stroke)',
    borderRadius: 9,
    outline: 'none',
    color: 'var(--owner-text)',
    fontSize: 14,
    fontWeight: 650,
  },
  nameSaveBtn: {
    minHeight: 40,
    padding: '8px 14px',
    border: 'none',
    borderRadius: 9,
    background: 'var(--owner-primary)',
    color: '#fff',
    cursor: 'pointer',
    fontSize: 13,
    fontWeight: 650,
  },
  nameCancelBtn: {
    minHeight: 40,
    padding: '8px 14px',
    border: '1px solid var(--owner-stroke)',
    borderRadius: 9,
    background: '#fff',
    color: 'var(--owner-text)',
    cursor: 'pointer',
    fontSize: 13,
  },
  editBtn: {
    minHeight: 40,
    padding: '8px 14px',
    border: '1px solid var(--owner-stroke)',
    borderRadius: 9,
    background: '#fff',
    color: 'var(--owner-text)',
    cursor: 'pointer',
    fontSize: 13,
  },
  actions: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'flex-end',
    flexWrap: 'wrap',
    gap: 8,
  },
};
