export const dashboardStyles = {
  page:              { boxSizing: 'border-box', height: '100vh', overflowY: 'auto', overflowX: 'hidden', padding: 'clamp(12px, 2.4vw, 20px)', fontFamily: 'sans-serif', color: '#1f2937' },
  header:            { display: 'flex', justifyContent: 'space-between', alignItems: 'center', flexWrap: 'wrap', gap: 12, marginBottom: 12, paddingBottom: 14, borderBottom: '1px solid #e4e7ec' },
  cafeName:          { flex: '1 1 140px', minWidth: 0, fontWeight: 750, fontSize: 18, lineHeight: 1.35, wordBreak: 'break-word' },
  nameEditRow:       { display: 'flex', alignItems: 'center', flexWrap: 'wrap', gap: 6 },
  nameInput:         { minWidth: 0, width: 160, minHeight: 36, boxSizing: 'border-box', fontSize: 14, fontWeight: 700, padding: '7px 9px', borderRadius: 8, border: '1px solid #d0d5dd', outline: 'none' },
  nameSaveBtn:       { minHeight: 36, fontSize: 12, padding: '7px 12px', borderRadius: 8, background: '#1f2937', color: '#fff', border: 'none', cursor: 'pointer' },
  nameCancelBtn:     { minHeight: 36, fontSize: 12, padding: '7px 12px', borderRadius: 8, background: '#fff', border: '1px solid #d0d5dd', color: '#475467', cursor: 'pointer' },
  headerRight:       { display: 'flex', flex: '0 1 auto', maxWidth: '100%', flexWrap: 'wrap', gap: 8, alignItems: 'center' },
  toggleBtn:         { minHeight: 36, padding: '7px 12px', borderRadius: 999, border: '1px solid #d0d5dd', background: '#fff', color: '#475467', cursor: 'pointer', fontSize: 12, fontWeight: 700 },
  acceptingOn:       { borderColor: '#a6d8bb', background: '#ecfdf3', color: '#16744a' },
  aiOn:              { borderColor: '#f1cf8f', background: '#fffaeb', color: '#8a5d00' },
  toggleOff:         { borderColor: '#e4e7ec', background: '#f9fafb', color: '#667085' },
  noticeEditBtn:     { minHeight: 36, fontSize: 12, padding: '7px 12px', borderRadius: 8, border: '1px solid #d0d5dd', background: '#fff', color: '#475467', cursor: 'pointer' },
  noticeDeleteBtn:   { minHeight: 36, fontSize: 12, padding: '7px 12px', borderRadius: 8, border: '1px solid #f2c8c4', background: '#fff', color: '#b42318', cursor: 'pointer' },
  noticeEdit:        { margin: '12px 0', display: 'flex', flexDirection: 'column', gap: 6 },
  noticeInput:       { fontSize: 13, padding: '10px 12px', borderRadius: 8, border: '1px solid #d0d5dd', outline: 'none', resize: 'vertical', fontFamily: 'sans-serif' },
  noticeActions:     { display: 'flex', alignItems: 'center', flexWrap: 'wrap', gap: 6, justifyContent: 'flex-end' },
  noticeCount:       { fontSize: 12, color: '#98a2b3', marginRight: 'auto' },
  tabs:              { display: 'flex', gap: 4, marginBottom: 16, borderBottom: '1px solid #e4e7ec', overflowX: 'auto' },
  tab:               { flex: '1 0 auto', justifyContent: 'center', minHeight: 42, padding: '8px 12px', background: 'none', border: 'none', cursor: 'pointer', fontSize: 13, color: '#667085', display: 'flex', alignItems: 'center', gap: 6, whiteSpace: 'nowrap' },
  tabActive:         { color: '#1f2937', fontWeight: 700, borderBottom: '2px solid #1f2937', marginBottom: -1 },
  badge:             { background: '#b42318', color: '#fff', borderRadius: 999, padding: '1px 6px', fontSize: 10, lineHeight: 1.4 },
  empty:             { textAlign: 'center', color: '#aaa', padding: '40px 0' },
  section:           { marginBottom: 20, borderRadius: 8, transition: 'background 0.15s' },
  sectionDragOver:   { background: '#f0f7ff', outline: '2px dashed #2196f3', outlineOffset: 2 },
  sectionTitle:      { fontSize: 13, fontWeight: 700, color: '#555', marginBottom: 8, display: 'flex', alignItems: 'center', gap: 6 },
  emptySlot:         { fontSize: 13, color: '#ccc', padding: '12px 0', borderTop: '1px dashed #eee' },
  moreBtn:           { display: 'block', width: '100%', minHeight: 40, padding: '9px 12px', marginTop: 8, borderRadius: 8, border: '1px solid #e4e7ec', background: '#fff', color: '#475467', cursor: 'pointer', fontSize: 13 },
  historyFilter:     { display: 'flex', alignItems: 'center', gap: 8, margin: '8px 0 16px', flexWrap: 'wrap' },
  historyQuickFilters:{ display: 'flex', alignItems: 'center', gap: 4 },
  historyQuickBtn:   { minHeight: 36, fontSize: 12, padding: '7px 12px', borderRadius: 8, border: '1px solid #d0d5dd', background: '#fff', color: '#667085', cursor: 'pointer' },
  historyQuickBtnActive:{ background: '#1f2937', borderColor: '#1f2937', color: '#fff', fontWeight: 700 },
  dateInput:         { minHeight: 36, boxSizing: 'border-box', padding: '7px 10px', borderRadius: 8, border: '1px solid #d0d5dd', color: '#344054', fontSize: 13, outline: 'none' },
  historyError:      { display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: 12, margin: '12px 0', padding: '10px 12px', borderRadius: 8, border: '1px solid #f3c7c2', background: '#fff1f0', color: '#b42318', fontSize: 12 },
  historyRetryBtn:   { flexShrink: 0, padding: '5px 10px', borderRadius: 7, border: '1px solid #e4a8a1', background: '#fff', color: '#b42318', cursor: 'pointer', fontSize: 12, fontWeight: 600 },
};
