import { defineConfig } from 'vitest/config';

export default defineConfig({
  test: {
    setupFiles: ['tests/unit-setup.mjs'],
    include: [
      'tests/ai-guardrails-docs.test.mjs',
      'tests/admin-ai-labs.test.mjs',
      'tests/api-docs.test.mjs',
      'tests/electron-navigation-policy.test.mjs',
      'tests/electron-auto-update.test.mjs',
      'tests/electron-panel-layout.test.mjs',
      'tests/electron-playback-controller.test.mjs',
      'tests/electron-current-track.test.mjs',
      'tests/kst.test.mjs',
      'tests/limits.test.mjs',
      'tests/music-filter.test.mjs',
      'tests/music-labeling.test.mjs',
      'tests/owner-session.test.mjs',
      'tests/owner-music-resource.test.mjs',
      'tests/owner-bgm-bridge.test.mjs',
      'tests/owner-bgm-storage.test.mjs',
      'tests/owner-playback-cleanup.test.mjs',
      'tests/owner-playback-bridge.test.mjs',
      'tests/owner-playback-recovery.test.mjs',
      'tests/owner-playback-session.test.mjs',
      'tests/owner-playback-transition.test.mjs',
      'tests/playback-leader-registry.test.mjs',
      'tests/playback-history-policy.test.mjs',
      'tests/playback-payload.test.mjs',
      'tests/pagination.test.mjs',
      'tests/platforms.test.mjs',
      'tests/public-response.test.mjs',
      'tests/qr-image.test.mjs',
      'tests/security-headers.test.mjs',
      'tests/time-policy.test.mjs',
      'tests/transition.test.mjs',
      'tests/validate.test.mjs',
    ],
    pool: 'forks',
    singleFork: true,
    fileParallelism: false,
  },
});
